export type ProjectUnit = {
  type: string;
  area: string;
  price: string;
};

export type Project = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  status: "Under Construction" | "Ready to Move" | "Off-Plan";
  type: string;
  developer: string;
  location: string;
  address: string;
  price: string;
  priceValue: number;
  completionDate: string;
  totalUnits: number;
  totalFloors: number;
  description: string;
  highlights: string[];
  amenities: string[];
  images: string[];
  units: ProjectUnit[];
  tags: string[];
  agentName: string;
  agentPhone: string;
  agentPhoto: string;
};

export const PROJECTS: Project[] = [
  {
    id: "one-canal-road",
    slug: "one-canal-road",
    name: "One Canal Road",
    tagline: "Redefining vertical luxury on Lahore's most iconic boulevard.",
    status: "Under Construction",
    type: "High-Rise Apartment",
    developer: "Zameen Developments",
    location: "Gulberg",
    address: "Canal Bank Road, Gulberg, Lahore",
    price: "From ? 150M",
    priceValue: 150000000,
    completionDate: "Q4 2026",
    totalUnits: 240,
    totalFloors: 38,
    description:
      "One Canal Road is the pinnacle of luxury vertical living in Lahore. Designed by world-renowned architects and developed by Zameen Developments, it offers unparalleled panoramic views of the Lahore Canal. Each residence is crafted with premium Italian marble, smart home automation, and floor-to-ceiling windows that frame the city skyline. With 38 floors of ultra-luxury apartments, it sets a new benchmark for high-end urban living in Pakistan.",
    highlights: [
      "LDA & NOC approved",
      "Prime Canal Bank Road frontage",
      "Smart home automation in every unit",
      "Floor-to-ceiling double-glazed windows",
      "Italian marble & premium finishes",
      "Rooftop infinity pool & sky lounge",
    ],
    amenities: [
      "Infinity Pool",
      "Private Cinema",
      "Fitness Center",
      "24/7 Concierge",
      "Business Lounge",
      "Children Play Area",
      "Covered Parking",
      "High-Speed Elevators",
      "Backup Generator",
      "CCTV Surveillance",
      "Rooftop Sky Lounge",
      "Valet Parking",
    ],
    images: [
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
    ],
    units: [
      { type: "Studio",    area: "650 sqft",  price: "From ? 50M"  },
      { type: "1 Bedroom", area: "1,100 sqft", price: "From ? 95M"  },
      { type: "2 Bedroom", area: "1,800 sqft", price: "From ? 150M" },
      { type: "3 Bedroom", area: "2,600 sqft", price: "From ? 220M" },
      { type: "Penthouse", area: "4,200 sqft", price: "On Request"  },
    ],
    tags: ["Ultra Luxury", "Smart Home"],
    agentName: "Sheikh Asadullah",
    agentPhone: "+92 300 000 0001",
    agentPhoto: "/hero_background.jpg",
  },
  {
    id: "dha-prism",
    slug: "dha-prism",
    name: "Prism Signature Villas",
    tagline: "Exclusive golf-front villas in Lahore's most prestigious enclave.",
    status: "Ready to Move",
    type: "Luxury Villa",
    developer: "DHA Lahore",
    location: "DHA Lahore",
    address: "DHA Phase 9 Prism, Lahore",
    price: "From ? 85M",
    priceValue: 85000000,
    completionDate: "Ready Now",
    totalUnits: 80,
    totalFloors: 2,
    description:
      "Prism Signature Villas represent the gold standard of gated community living in DHA Lahore. These meticulously planned 1 and 2 Kanal villas offer sweeping golf course views, lush landscaped gardens, and interiors finished to the highest international standards. Each villa is fully approved by DHA and comes with title deed transfer on possession.",
    highlights: [
      "DHA approved with title deed",
      "Golf course frontage available",
      "1 & 2 Kanal plot sizes",
      "Lush landscaped gardens",
      "Gated with 24/7 security",
      "Immediate possession available",
    ],
    amenities: [
      "Gated Community",
      "Golf Course Access",
      "24/7 Security",
      "Landscaped Parks",
      "Community Club",
      "Swimming Pool",
      "Mosque",
      "Community Centre",
      "Jogging Track",
      "Underground Utilities",
      "Wide Service Roads",
      "CCTV Surveillance",
    ],
    images: [
      "/the_meridian_villas.jpg",
      "/emirates_mall_residences.jpg",
      "/hero_background.jpg",
      "/the_meridian_villas.jpg",
      "/emirates_mall_residences.jpg",
    ],
    units: [
      { type: "1 Kanal Villa",   area: "10 Marla",  price: "From ? 85M"  },
      { type: "2 Kanal Villa",   area: "2 Kanal",   price: "From ? 160M" },
      { type: "Corner 2 Kanal",  area: "2 Kanal+",  price: "From ? 185M" },
    ],
    tags: ["Golf Course View", "Premium"],
    agentName: "Hassan Khan",
    agentPhone: "+92 300 000 0002",
    agentPhoto: "/emirates_mall_residences.jpg",
  },
  {
    id: "lahore-sky",
    slug: "lahore-sky",
    name: "Lahore Sky",
    tagline: "The future of modern living meets IT innovation.",
    status: "Under Construction",
    type: "High-Rise Apartment",
    developer: "OZ Developers",
    location: "Ferozepur Road",
    address: "Ferozepur Road, Lahore",
    price: "From ? 40M",
    priceValue: 40000000,
    completionDate: "Q2 2027",
    totalUnits: 320,
    totalFloors: 28,
    description:
      "Lahore Sky by OZ Developers is a landmark mixed-use development integrating residential luxury with a state-of-the-art IT Park. The project offers affordable yet premium apartments, complemented by world-class commercial spaces, making it the ideal investment for both end-users and high-yield investors.",
    highlights: [
      "LDA approved",
      "Integrated IT Park & commercial spaces",
      "High rental yield potential",
      "Easy installment plan available",
      "Located on main Ferozepur Road",
      "Modern smart city infrastructure",
    ],
    amenities: [
      "IT Park",
      "Food Court",
      "Gym & Spa",
      "Swimming Pool",
      "24/7 Security",
      "CCTV",
      "Covered Parking",
      "Prayer Area",
      "Backup Power",
      "High-Speed Internet",
      "Rooftop Garden",
      "Co-working Spaces",
    ],
    images: [
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
    ],
    units: [
      { type: "Studio",    area: "450 sqft",  price: "From ? 40M" },
      { type: "1 Bedroom", area: "850 sqft",  price: "From ? 65M" },
      { type: "2 Bedroom", area: "1,400 sqft", price: "From ? 95M" },
    ],
    tags: ["IT Park", "Commercial"],
    agentName: "Mian Hamad Mahmood",
    agentPhone: "+92 300 000 0003",
    agentPhoto: "/the_meridian_villas.jpg",
  },
  {
    id: "union-living",
    slug: "union-living",
    name: "Union Living",
    tagline: "Premium canal-front living for discerning families.",
    status: "Ready to Move",
    type: "High-Rise Apartment",
    developer: "Union Developers",
    location: "Canal Bank Road",
    address: "Canal Bank Road, Lahore",
    price: "From ? 65M",
    priceValue: 65000000,
    completionDate: "Ready Now",
    totalUnits: 180,
    totalFloors: 22,
    description:
      "Union Living by Union Developers offers thoughtfully designed canal-facing apartments in the heart of Lahore's most vibrant corridor. With a focus on family living and community, it features generous floor plans, premium amenities, and direct access to the canal boulevard promenade.",
    highlights: [
      "Canal-facing units available",
      "Family-oriented community",
      "Immediate possession",
      "Underground basement parking",
      "LDA & NOC approved",
      "Premium finishing by German brands",
    ],
    amenities: [
      "Canal Promenade Access",
      "Gymnasium",
      "Swimming Pool",
      "Rooftop Lounge",
      "24/7 Security",
      "CCTV",
      "Basement Parking",
      "Backup Generator",
      "Prayer Area",
      "Laundry Services",
      "Community Room",
      "Kids Play Area",
    ],
    images: [
      "/emirates_mall_residences.jpg",
      "/hero_background.jpg",
      "/the_meridian_villas.jpg",
      "/emirates_mall_residences.jpg",
      "/hero_background.jpg",
    ],
    units: [
      { type: "2 Bedroom", area: "1,400 sqft", price: "From ? 65M"  },
      { type: "3 Bedroom", area: "2,000 sqft", price: "From ? 95M"  },
      { type: "4 Bedroom", area: "2,800 sqft", price: "From ? 140M" },
    ],
    tags: ["Family Oriented", "Premium Amenities"],
    agentName: "Sheikh Asadullah",
    agentPhone: "+92 300 000 0001",
    agentPhoto: "/hero_background.jpg",
  },
  {
    id: "bahria-town-heights",
    slug: "bahria-town-heights",
    name: "Bahria Sky",
    tagline: "High-yield investment in Lahore's most iconic planned community.",
    status: "Under Construction",
    type: "High-Rise Apartment",
    developer: "Bahria Town",
    location: "Bahria Town",
    address: "Bahria Town, Main Boulevard, Lahore",
    price: "From ? 55M",
    priceValue: 55000000,
    completionDate: "Q1 2027",
    totalUnits: 400,
    totalFloors: 30,
    description:
      "Bahria Sky is an iconic mixed-use tower within the iconic Bahria Town community. With direct mall access, a vibrant retail and F&B podium, and luxury residential floors above, it promises exceptional rental yields and a lifestyle second to none in Pakistan.",
    highlights: [
      "Bahria Town approved",
      "Direct Grand Mosque views",
      "Integrated with Bahria Mall",
      "High rental yield — up to 9% annually",
      "Global-standard property management",
      "Flexible installment plans",
    ],
    amenities: [
      "Mall Integration",
      "Theme Park Access",
      "Golf Course",
      "24/7 Security",
      "Swimming Pool",
      "Fitness Club",
      "Rooftop Restaurant",
      "Business Centre",
      "Medical Clinic",
      "Schools Nearby",
      "Sports Complex",
      "Mosque",
    ],
    images: [
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
    ],
    units: [
      { type: "Studio",    area: "500 sqft",  price: "From ? 55M" },
      { type: "1 Bedroom", area: "950 sqft",  price: "From ? 75M" },
      { type: "2 Bedroom", area: "1,600 sqft", price: "From ? 110M" },
    ],
    tags: ["Mall Integration", "High Yield"],
    agentName: "Hassan Khan",
    agentPhone: "+92 300 000 0002",
    agentPhoto: "/emirates_mall_residences.jpg",
  },
  {
    id: "dha-penthouse",
    slug: "dha-penthouse",
    name: "The Penta DHA",
    tagline: "Lahore's most exclusive penthouse residences.",
    status: "Ready to Move",
    type: "High-Rise Apartment",
    developer: "Izhar Monnoo",
    location: "DHA Lahore",
    address: "DHA Phase 5, Commercial Zone, Lahore",
    price: "From ? 250M",
    priceValue: 250000000,
    completionDate: "Ready Now",
    totalUnits: 24,
    totalFloors: 18,
    description:
      "The Penta DHA is an ultra-exclusive boutique tower by the legendary Izhar Monnoo Developers, offering just 24 bespoke penthouses. Each residence spans an entire floor, with private terraces, panoramic DHA views, and bespoke interiors customized to the owner's specifications. The ultimate statement of luxury in Lahore.",
    highlights: [
      "Entire floor per unit",
      "Private terrace with DHA views",
      "Bespoke interior customization",
      "Only 24 units — ultra exclusive",
      "DHA Phase 5 prime location",
      "Private lift lobby per floor",
    ],
    amenities: [
      "Private Terraces",
      "Rooftop Infinity Pool",
      "Private Elevator Lobby",
      "Concierge Butler",
      "Private Cinema Room",
      "Wine Cellar",
      "Smart Home Automation",
      "Heated Flooring",
      "Spa & Wellness",
      "Guest Suites",
      "Private Parking Pods",
      "24/7 Security",
    ],
    images: [
      "/hero_background.jpg",
      "/the_meridian_villas.jpg",
      "/emirates_mall_residences.jpg",
      "/hero_background.jpg",
      "/the_meridian_villas.jpg",
    ],
    units: [
      { type: "Penthouse",        area: "6,000 sqft",  price: "From ? 250M" },
      { type: "Sky Penthouse",    area: "8,500 sqft",  price: "From ? 380M" },
      { type: "Grand Penthouse",  area: "12,000 sqft", price: "On Request"   },
    ],
    tags: ["Penthouse", "Exclusive"],
    agentName: "Mian Ammar Mehmood",
    agentPhone: "+92 300 000 0000",
    agentPhoto: "/hero_background.jpg",
  },
  {
    id: "gulberg-galleria-residences",
    slug: "gulberg-galleria-residences",
    name: "Galleria Residences",
    tagline: "A boutique urban sanctuary in the heart of Gulberg.",
    status: "Under Construction",
    type: "High-Rise Apartment",
    developer: "Gulberg Group",
    location: "Gulberg",
    address: "Gulberg III, Main Boulevard, Lahore",
    price: "From ? 120M",
    priceValue: 120000000,
    completionDate: "Q3 2026",
    totalUnits: 120,
    totalFloors: 20,
    description:
      "Galleria Residences is a sophisticated boutique high-rise located in the pulsating heart of Gulberg. Offering just 120 premium apartments above a luxury retail podium, it delivers a curated lifestyle experience with walkable access to Lahore's best dining, retail, and business hubs.",
    highlights: [
      "LDA approved",
      "Boutique low-density development",
      "Luxury retail podium",
      "Gulberg III prime location",
      "Walking distance to M.M. Alam Road",
      "Serviced apartment option",
    ],
    amenities: [
      "Luxury Retail Podium",
      "Sky Deck",
      "Infinity Pool",
      "Fitness Center",
      "24/7 Concierge",
      "Valet Parking",
      "Business Lounge",
      "Rooftop Restaurant",
      "CCTV",
      "Smart Locks",
      "Backup Power",
      "High-Speed Elevators",
    ],
    images: [
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
    ],
    units: [
      { type: "1 Bedroom", area: "1,200 sqft", price: "From ? 120M" },
      { type: "2 Bedroom", area: "1,900 sqft", price: "From ? 185M" },
      { type: "3 Bedroom", area: "2,700 sqft", price: "From ? 260M" },
    ],
    tags: ["Boutique", "Commercial Hub"],
    agentName: "Sheikh Asadullah",
    agentPhone: "+92 300 000 0001",
    agentPhoto: "/the_meridian_villas.jpg",
  },
  {
    id: "lake-city-villas",
    slug: "lake-city-villas",
    name: "Lake City Golf Villas",
    tagline: "Lakeside golf estate living on Raiwind Road.",
    status: "Ready to Move",
    type: "Luxury Villa",
    developer: "Lake City Holdings",
    location: "Raiwind Road",
    address: "Lake City, Raiwind Road, Lahore",
    price: "From ? 180M",
    priceValue: 180000000,
    completionDate: "Ready Now",
    totalUnits: 55,
    totalFloors: 2,
    description:
      "Lake City Golf Villas offer an unmatched lifestyle in Lahore's only international-standard golf estate. Set against the backdrop of a championship 18-hole golf course and scenic lake, these villas combine natural tranquility with world-class amenities and top-grade construction by Lake City Holdings.",
    highlights: [
      "18-hole golf course frontage",
      "Scenic lakeside location",
      "Gated estate with 24/7 security",
      "International-standard finishes",
      "Immediate possession available",
      "Lake City community access",
    ],
    amenities: [
      "Championship Golf Course",
      "Lake Access",
      "Clubhouse",
      "Swimming Pool",
      "Tennis Courts",
      "24/7 Security",
      "Mosque",
      "International School Nearby",
      "Hospital Nearby",
      "Jogging Trails",
      "Community Park",
      "Underground Services",
    ],
    images: [
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
    ],
    units: [
      { type: "1 Kanal Villa",  area: "10 Marla",  price: "From ? 180M" },
      { type: "2 Kanal Villa",  area: "2 Kanal",   price: "From ? 320M" },
    ],
    tags: ["Golf Estate", "Gated Community"],
    agentName: "Hassan Khan",
    agentPhone: "+92 300 000 0002",
    agentPhoto: "/emirates_mall_residences.jpg",
  },
  {
    id: "johar-town-commercial",
    slug: "johar-town-commercial",
    name: "The Financial Tower",
    tagline: "Lahore's premier corporate address in Johar Town.",
    status: "Under Construction",
    type: "Commercial Space",
    developer: "United Lifestyle",
    location: "Johar Town",
    address: "Johar Town, Main Boulevard, Lahore",
    price: "From ? 30M",
    priceValue: 30000000,
    completionDate: "Q2 2026",
    totalUnits: 200,
    totalFloors: 24,
    description:
      "The Financial Tower by United Lifestyle is engineered for Lahore's growing corporate sector. With Grade-A office floors, retail spaces, a dedicated food court, and international-standard infrastructure, it sets a new standard for commercial real estate investment in Johar Town — one of Lahore's fastest-growing business districts.",
    highlights: [
      "LDA approved",
      "Grade-A office specification",
      "Strategic Johar Town location",
      "High ROI commercial investment",
      "Dedicated food court & retail",
      "Easy installment plans",
    ],
    amenities: [
      "Grade-A Office Floors",
      "Food Court",
      "Retail Podium",
      "Parking (800 cars)",
      "Conference Facilities",
      "High-Speed Internet",
      "Backup Power",
      "CCTV",
      "Access Control",
      "Security Personnel",
      "Prayer Area",
      "Prayer Hall",
    ],
    images: [
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
      "/the_meridian_villas.jpg",
      "/hero_background.jpg",
      "/emirates_mall_residences.jpg",
    ],
    units: [
      { type: "Office Unit",    area: "500 sqft",  price: "From ? 30M"  },
      { type: "Large Office",   area: "1,200 sqft", price: "From ? 65M"  },
      { type: "Retail Unit",    area: "300 sqft",   price: "From ? 25M"  },
      { type: "Full Floor",     area: "5,000 sqft", price: "On Request"  },
    ],
    tags: ["Corporate", "High ROI"],
    agentName: "Mian Hamad Mahmood",
    agentPhone: "+92 300 000 0003",
    agentPhoto: "/the_meridian_villas.jpg",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}
